### PR TITLE
fix: fix a unit test error

### PR DESCRIPTION
**Pull request by GongHeng2017**
ChineseAnalyzer now supports numeric

### CODE REVIEW

**Comment by GongHeng2017** [comment]
@LocutusOfBorg @alanw @Kakueeen

**Review by alanw — APPROVED** [review]

**Comment by LocutusOfBorg** [comment]
thanks!

**Comment by LocutusOfBorg** [comment]
@GongHeng2017 looks like big endian machines are really sad now

```
[ RUN      ] IndexOutputTest.testWriteVLong
[       OK ] IndexOutputTest.testWriteVLong (0 ms)
[ RUN      ] IndexOutputTest.testWriteString
[       OK ] IndexOutputTest.testWriteString (0 ms)
[ RUN      ] IndexOutputTest.testWriteChars
[       OK ] IndexOutputTest.testWriteChars (0 ms)
[ RUN      ] IndexOutputTest.testCopyBytes
Segmentation fault (core dumped)
make[1]: *** [debian/rules:30: override_dh_auto_test] Error 139
make[1]: Leaving directory '/build/lucene++-lHQlnk/lucene++-3.0.8'
make: *** [debian/rules:7: binary-arch] Error 2
dpkg-buildpackage: error: debian/rules binary-arch subprocess returned exit status 2

```

**Comment by LocutusOfBorg** [comment]
full log here
https://launchpadlibrarian.net/526944068/buildlog_ubuntu-hirsute-s390x.lucene++_3.0.8-4~build1_BUILDING.txt.gz

**Comment by LocutusOfBorg** [comment]
(nevermind might be due to new compiler or something different)

**Pull request merged**
